version: "3.9"

services:
    redis:
        image: redis:6.2.6
        container_name: fp-cache
        expose:
            - 6379
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        volumes:
            - ./redis/data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    database:
        image: postgres:10.5
        container_name: fp-db
        ports:
            - "5432:5432"
        env_file:
            - db.env
        volumes:
            -   type: bind
                source: ./database/init/init.sql
                target: /docker-entrypoint-initdb.d/init.sql
    backend:
        container_name: fp-server
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            -   type: bind
                source: ./backend
                target: /home/admin/
            
        depends_on:
            - database
            - redis
        #command: nodemon server.js
    frontend:
        container_name: fp-client
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: app
        user: node
        volumes:
            -   type: bind
                source: ./frontend
                target: /app
        ports:
            - 3000:3000
        env_file:
            - .env
        
        command: npm start
    webserver:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod
        image: nginx
        container_name: fp-nx
        restart: always
        
        volumes:
            -   type: bind
                source: ./nginx/conf.d/
                target: /etc/nginx/conf.d/
        environment:
            - API_SERVER=backend:8000
        env_file:
            - .env
        command: >
            /bin/sh -c
            "envsubst '
            $${DOMAIN_URL}
            $${API_SERVER}
            '< /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"

