version: "3.9"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/app
        env_file:
            - .env
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - database
    database:
        image: postgres:14.5
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod
        image: nginx
        restart: always
        ports:
            - 80:80
        environment:
            - API_SERVER=http://backend:${API_PORT}
        
        

