version: "3.9"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/app
        environment:
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_DATABASE=tarea1
            - DB_HOST=postgres
            - DB_PORT=5432
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - postgres
    postgres:
        image: 'bitnami/postgresql:latest'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRESQL_DATABASE=tarea1
        ports:
            - 5432:5432
    frontend:
        container_name: fp-client
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: app
        user: node
        volumes:
            -   type: bind
                source: ./frontend
                target: /app
        ports:
            - 3000:3000
        env_file:
            - .env
        
        command: npm start
    webserver:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod
        image: nginx
        container_name: fp-nx
        restart: always
        
        volumes:
            -   type: bind
                source: ./nginx/conf.d/
                target: /etc/nginx/conf.d/
        environment:
            - API_SERVER=backend:8000
        env_file:
            - .env
        ports: 
            - 80:80
        command: >
            /bin/sh -c
            "envsubst '
            $${API_SERVER}
            '< /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"

