version: "3.9"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - database
    database:
        image: postgres:14.5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=tarea1
    frontend:
        container_name: fp-client
        build:
            context: ./frontend/
            dockerfile: Dockerfile
            target: builder
        user: node
        volumes:
            - ./frontend/:/app
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
    webserver:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod
        image: nginx
        container_name: fp-nx
        restart: always
        
        volumes:
            -   type: bind
                source: ./nginx/conf.d/
                target: /etc/nginx/conf.d/
        environment:
            - API_SERVER=backend:8000
        env_file:
            - .env
        ports: 
            - 80:80
        command: >
            /bin/sh -c
            "envsubst '
            $${API_SERVER}
            '< /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"

