version: "3.9"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/app
        env_file:
            - .env
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - database
    database:
        image: postgres:14.5
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - 5432:5432
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: prod
        image: nginx
        container_name: fp-nx
        restart: always
        
        volumes:
            -   type: bind
                source: ./nginx/conf.d/
                target: /etc/nginx/conf.d/
        environment:
            - API_SERVER=backend:8000
        env_file:
            - .env
        ports: 
            - 80:80
        command: >
            /bin/sh -c
            "envsubst '
            $${API_SERVER}
            '< /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"

